In [5]:
import numpy as np

In [8]:
# 행렬을 만들기 위해서는 numpy의 array 메소드를 쓰고 파라미터로 리스트를 넘겨주면 되는데요.
# 행렬을 만들고 싶으면 2차원 배열을 쓰면 됩니다.

A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

# 이렇게 2차원 배열을 썼습니다. 2차원 배열이라는 것은 리스트 안에 리스트가 있다는 것인데요.
# 지금 보시면 리스트 안에 리스트 네 개를 넣었죠? 이렇게 하면 numpy가 4 x 3 행렬을 만들어줍니다.
# 이것을 변수 A에 저장하겠습니다.

A

# 이것은 4 x 3 행렬이니까 행이 네 개 잇고 열이 세 개 있다는 것입니다.
# 1,3,4,7 이것이 하나의 열이고, -1,2,1,5 이것이 또 하나의 열이고, 2,2,2,6 이것이 마지막 열입니다.

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [9]:
# 하나 더 만들어보겠습니다. 이번에는 3 x 2 행렬을 만들겠습니다.

B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])

B

# 우선 행이 세 개 있습니다. 그리고 0,-1,5 이것이 하나의 열이고, 1,3,2 이것이 또 다른 열인 것이죠.

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [10]:
# A와 B는 우리가 원하는 값들을 넣어서 만든 것인데요. 이번에는 행렬에 랜덤한 값들을 넣겠습니다.
# np.random.rand()를 하고 괄호 안에 차원을 쓰면 됩니다. 3 x 5 행렬을 만드로 싶으면 3, 5를 쓰면 되는 것이죠.

C = np.random.rand(3, 5)

# 이것을 변수 C에 넣어주겠습니다

C

# 그러면 보시다시피 3 x 5 행렬이 나오는데, 0과 1사이의 랜덤한 값들이 들어가 있습니다.

array([[0.01885466, 0.34138377, 0.29547086, 0.700379  , 0.99961424],
       [0.39070729, 0.2348571 , 0.55984346, 0.1403149 , 0.90235927],
       [0.09918316, 0.76298414, 0.28453191, 0.31381221, 0.51987388]])

In [12]:
# 만약 모든 값이 0인 행렬을 만들고 싶으면 zeros라는 메소드를 쓰고, 그 안에 차원을 쓰면 됩니다.
# 이번에는 2 x 4 행렬을 만들고 싶다고 가정합시다. zeros 메소드에는 그냥 (2,4)만 쓰는 것이 아니라
# **안에 괄호를 한 번 더 써줘야 합니다.** 이것을 꼭 기억해 주세요.

D = np.zeros((2, 4))

# 그리고 이것을 D라는 변수에 넣어주겠습니다. 그러면 2 x 4 행렬이 나오고 모든 값은 0입니다.

D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# 이제 행렬에서 원소를 받아오는 방법을 보겠습니다.
# 처음에 만들었던 행렬 A를 봅시다.

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [14]:
# 위에서 1행 3열의 원소를 받아오고 싶으면 어떻게 해야 될까요?
# 그냥 2차원 리스트의 원소를 받아오는 것과 똑같습니다.
# 행렬을 쓰고 대괄호 안에 행을 쓰고 그 다음에 대괄호 안에 열을 쓰면 되는 것이죠.

# A[1][3]

# 그런데 여기서 주의하셔야 할 것이 하나 있습니다. 우리가 받아오고 싶은 1행 3열이죠?
# 파이썬에서는 1부터 세는 것이 아니라 0부터 세는 것이기 때문에 
# 1행 3열을 받아오고 싶으면 [1][3]이 아니라 [0][2]를 써야 합니다.

A[0][2]

2

In [15]:
# 만약 아래와 같이 행렬의 크기를 넘어서는, 어떤 범위를 넘어서는 값을 쓰면 어떻게 될까요?

A[0][5]

# 당연히 오류가 나오겠죠?

IndexError: index 5 is out of bounds for axis 0 with size 3