In [1]:
import numpy as np

In [4]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

B = np.random.rand(3, 3)  # A는 원하는 값, B는 랜덤한 값을 넣었음.

In [5]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [6]:
B

array([[0.06991044, 0.28829286, 0.25509582],
       [0.70589311, 0.58736454, 0.53372973],
       [0.80193738, 0.44338859, 0.19763449]])

In [7]:
# 둘 다 3x3행렬임.
A + B  # 두 행렬의 합

array([[ 1.06991044, -0.71170714,  2.25509582],
       [ 3.70589311,  2.58736454,  2.53372973],
       [ 4.80193738,  1.44338859,  2.19763449]])

In [8]:
5 * A  # 스칼라곱

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [9]:
np.dot(A, B)  # 행렬곱

array([[0.96789208, 0.58770549, 0.11663507],
       [3.2253923 , 2.92638484, 2.22801588],
       [2.58940962, 2.62731315, 1.94938197]])

In [10]:
A @ B  # 쉬운 행렬곱 method

array([[0.96789208, 0.58770549, 0.11663507],
       [3.2253923 , 2.92638484, 2.22801588],
       [2.58940962, 2.62731315, 1.94938197]])

In [11]:
A @ B + (A + 2 * B)  # 여러 연산을 섞어서도 가능함. 일반적인 수학 연산의 순서로 진행됨.

array([[2.10771296, 0.16429121, 2.6268267 ],
       [7.63717853, 6.10111393, 5.29547533],
       [8.19328438, 4.51409033, 4.34465095]])