In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [4]:
# A의 전치행렬
A_transpose = np.transpose(A)
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [5]:
# A의 전치행렬 쉬운 방법
A_transpose2 = A.T
A_transpose2

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [6]:
# A의 단위행렬
I = np.identity(3)
I   # 3x3 단위행렬이 출력됨

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# 어떤 행렬과 단위행렬의 곱은 어떤 행렬의 값이 그대로 출력되어야 함.
A @ I   # 기존 행렬 A가 그대로 출력됨

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [8]:
# A의 역행렬
A_inverse = np.linalg.pinv(A)
# 위 함수는 역행렬이 없는 경우에도 역행렬과 최대한 비슷한 효과를 낼 수 있는 행렬을 return해줌.
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [9]:
# A와 A의 역행렬을 곱하면 단위행렬이 출력됨.
A @ A_inverse
# 대각선은 모두 1이 맞음. 그 외의 원소는 -16제곱의 형태로, 0과 매우 가깝게 출력됨.
# 컴퓨터가 소수 0을 다룰 때 완벽하게 표현하기 어렵기 때문임.

array([[ 1.00000000e+00,  7.77156117e-16, -8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00, -8.88178420e-16],
       [ 0.00000000e+00,  4.44089210e-16,  1.00000000e+00]])