In [15]:
### <- 이전 수업에 이어서
# 저번 영상에서는 데이터를 트레이닝 셋과 테스트 셋으로 나눴습니다. 이제 트레이닝 셋을 이용해서 선형 회귀 모델을 학습시켜보겠습니다. 그러기 위해서는 sklearn 라이브러리에서 선형 회귀 모델을 불러와야 하는데요. 
# from sklearn.linear_model import LinearRegression 이렇게 하면 됩니다. 그리고 셀을 다시 실행시키겠습니다. 사실 꼭 위에 쓸 필요는 없지만 module 불러오는 것은 위에서 한꺼번에 하는 것이 좋으니까 위에 다 몰아서 쓰겠습니다.
# 이제 이 LinearRegression 모델을 쓰면 선형 회귀를 쉽게 사용할 수 있습니다. 이전에는 우리가 하나하나 직접 구현을 했었는데 여기 sklearn에는 누가 이미 다 만들어 놓은 것입니다. 한번 사용해보겠습니다.

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import pandas as pd

In [2]:
boston_dataset = load_boston()

In [3]:
x = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)

In [4]:
x = x[['AGE']]

y = pd.DataFrame(boston_dataset.target, columns=['MEDV'])
y

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=5)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(404, 1)
(102, 1)
(404, 1)
(102, 1)


In [10]:
# LinearRegression을 쓰고 괄호를 열고 닫습니다. 그리고 이것을 모델이라는 변수에 저장하겠습니다.
model = LinearRegression()
# 이제 모델을 쓰고 fit이라는 메소드를 씁니다. 첫 파라미터로는 트레이닝 셋의 입력 변수 x_train이죠. 그리고 두 번째 파라미터로는 트레이닝 셋의 목표 변수 y_train이겠죠. 이렇게 하면 트레이닝 셋에 대한 학습이 끝납니다.
model.fit(x_train, y_train)

LinearRegression()

In [11]:
# 학습이 끝나면 이 모델 변수에 학습된 모델의 정보들이 있는데요. model.coef_를 하면 세타1의 값이 나옵니다.
model.coef_

array([[-0.12402883]])

In [12]:
# model.intercept_를 하면 세타0의 값이 나옵니다.
model.intercept_

# 이것을 해석해보자면 우리가 구한 최적선이 f(x) = 31.0417413 - 0.12402883x 이것이 우리가 구한 최적선입니다.

array([31.04617413])

In [14]:
# 이제 우리는 이 최적선이 예측을 잘 하는지 알고 싶습니다.
# 이 모델이 트레이닝 셋으로 학습을 한 것이기 때문에 트레이닐 셋으로 평가하면 신빙성이 떨어집니다. 그래서 아까 따로 빼둔 테스트 셋으로 평가를 해야 합니다.
# 우리가 구한 이 최적선으로 새 데이터에 대한 예측을 하려면 model.predict()를 쓰고 파라미터로는 테스트 셋의 입력 변수 x_test를 넘기겠습니다.
# 그리고 예측된 결과를 y_test_prediction이라는 변수에 저장하고 이것을 출력해보면 다음과 같이 쭉 나옵니다. 이것이 테스트 셋에 대한 예측값들인 겁니다.
y_test_prediction = model.predict(x_test)
y_test_prediction

array([[20.31768041],
       [28.14389953],
       [22.84786852],
       [18.64329122],
       [24.62148078],
       [19.99520545],
       [19.75955068],
       [22.79825699],
       [20.92542167],
       [21.74401194],
       [23.29437231],
       [25.41526529],
       [21.53316293],
       [25.94858925],
       [23.76568186],
       [24.55946636],
       [18.64329122],
       [18.64329122],
       [22.00447248],
       [18.64329122],
       [18.89134887],
       [18.90375176],
       [21.33471681],
       [22.71143681],
       [28.46637448],
       [19.06498923],
       [24.31140871],
       [22.05408402],
       [26.32067574],
       [26.59353916],
       [19.0153777 ],
       [18.85414022],
       [19.30064401],
       [18.7301114 ],
       [28.76404367],
       [18.92855752],
       [21.5579687 ],
       [19.21382383],
       [19.69753626],
       [29.08651863],
       [19.56110455],
       [18.64329122],
       [21.02464473],
       [20.14404005],
       [24.72070384],
       [25

In [16]:
# 그런데 이것은 예측값인 것이고, 변수 y_test. 이 y_test에는 테스트 셋의 실제 목표 변수 값들이 들어가 있습니다.
# 밑에 있는 이 예측 값들과 실제 아웃풋 값을 비교홰서 우리의 모델을 평가하고 싶은데요.
# 보통은 '평균 제곱근 오차'라는 것을 쓴다고 전에 설명드렸습니다. 그냥 평균 제곱 오차에 루트를 한 것입니다.
# 그걸 하기 위해서 평균 제곱 오차를 구하는 함수를 불러오겠습니다.
# import mean_square_error을 입력하고 다시 실행하고 밑으로 내려와서 mean_square_error 함수의 파라미터로 비교하고 싶은 y_test랑 y_test_prediction을 넣으면 됩니다.
mean_squared_error(y_test, y_test_prediction) ** 0.5
# 이렇게 하면 평균 제곱 오차가 나오는데 우리는 평균 제곱 오차가 아니라 평균 제곱근 오차를 구하고 싶으니까 여기에 루트를 해야 합니다. 루트는 0.5 제곱과 같으니 이렇게 별표 두 개(**)를 쓰고 0.5를 쓰면 됩니다.

# 실행하면 8.24 정도가 나오네요. 트레이닝 셋으로 모델을 학습시키고 그 모델을 테스트 셋에 적용해서 평가를 해봤더니 오차가 이 정도 나온 것입니다.
# 이 모델로 집값을 예측하면 한 8천 달러 정도의 오차가 있다고 생각하시면 됩니다.

8.236881612652455